### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-kt1dg#4]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by vshubhams** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/82999004/166309705-9e486601-8b1a-4431-9991-640eea281a45.png)
